name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Log java version
      run: java -version && mvn --version
    - name: Build
      run: mvn --no-transfer-progress package
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: target/BungeeGCloud-*.jar
